version: "3"
services:
  mysqldb:
   image: mysql
   container_name: mysqldb
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
   volumes:
     - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"
# create a folder "scripts" and place the database.sql inside it.
  servletapplication:
   image: servletapplication
   container_name: servletapplication
   ports:
     - "9090:8080"
